-- begin ORDERMANAGEMENTWORK_ADDRESS
alter table ORDERMANAGEMENTWORK_ADDRESS add constraint FK_ORDERMANAGEMENTWORK_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGEMENTWORK_CUSTOMER(ID)^
create index IDX_ORDERMANAGEMENTWORK_ADDRESS_ON_CUSTOMER on ORDERMANAGEMENTWORK_ADDRESS (CUSTOMER_ID)^
-- end ORDERMANAGEMENTWORK_ADDRESS
-- begin ORDERMANAGEMENTWORK_ORDER
alter table ORDERMANAGEMENTWORK_ORDER add constraint FK_ORDERMANAGEMENTWORK_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGEMENTWORK_CUSTOMER(ID)^
create index IDX_ORDERMANAGEMENTWORK_ORDER_ON_CUSTOMER on ORDERMANAGEMENTWORK_ORDER (CUSTOMER_ID)^
-- end ORDERMANAGEMENTWORK_ORDER
-- begin ORDERMANAGEMENTWORK_LINE_ITEM
alter table ORDERMANAGEMENTWORK_LINE_ITEM add constraint FK_ORDERMANAGEMENTWORK_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERMANAGEMENTWORK_PRODUCT(ID)^
alter table ORDERMANAGEMENTWORK_LINE_ITEM add constraint FK_ORDERMANAGEMENTWORK_LINE_ITEM_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGEMENTWORK_ORDER(ID)^
create index IDX_ORDERMANAGEMENTWORK_LINE_ITEM_ON_PRODUCT on ORDERMANAGEMENTWORK_LINE_ITEM (PRODUCT_ID)^
create index IDX_ORDERMANAGEMENTWORK_LINE_ITEM_ON_ORDER on ORDERMANAGEMENTWORK_LINE_ITEM (ORDER_ID)^
-- end ORDERMANAGEMENTWORK_LINE_ITEM
-- begin ORDERMANAGEMENTWORK_DOCUMENT
alter table ORDERMANAGEMENTWORK_DOCUMENT add constraint FK_ORDERMANAGEMENTWORK_DOCUMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table ORDERMANAGEMENTWORK_DOCUMENT add constraint FK_ORDERMANAGEMENTWORK_DOCUMENT_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGEMENTWORK_ORDER(ID)^
create index IDX_ORDERMANAGEMENTWORK_DOCUMENT_ON_FILE on ORDERMANAGEMENTWORK_DOCUMENT (FILE_ID)^
create index IDX_ORDERMANAGEMENTWORK_DOCUMENT_ON_ORDER on ORDERMANAGEMENTWORK_DOCUMENT (ORDER_ID)^
-- end ORDERMANAGEMENTWORK_DOCUMENT
